# galaxy.yml for jcook3701.utils
#
# SPDX-FileCopyrightText: Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
namespace: "jcook3701"
name: "utils"
version: "1.0.0"
authors:
  - "Jared Cook @jcook3701"
license:
  - AGPL-3.0-or-later
readme: ./README.md
description: >
  Ansible utilities for assiting automation processes.

tags:
  - lab
  - homelab
  - automation
  - infrastructure

dependencies:
  # jcook3701.pkgs: "*"
  # jcook3701.utils: "*"
  community.general: ">=12.0.0"

build_ignore:
  - "*.tar.gz"
  - ".gitignore"
  - ".gitattributes"
  - ".git"
  - ".github"
  - ".ansible-lint*"
  - ".mypy_cache"
  - ".pytest_cache"
  - ".ruff_cache"
  - ".yamllint"
  - ".pre-commit-config.yaml"
  - "pyproject.toml"
  - "galaxy-importer.cfg"
  - "cspell.json"
  - "autodoc.config.yaml"
  - ".cookiecutter_includes"
  - "importer_result.json"
  - "tests"
  - "docs"
  - ".venv"
  - "Makefile"

repository: >-
  https://github.com/jcook3701/jcook3701.utils
documentation: >-
  https://github.com/jcook3701/jcook3701.utils/blob/master/README.md
homepage: >-
  https://github.com/jcook3701/jcook3701.utils
issues: >-
  https://github.com/jcook3701/jcook3701.utils/issues
...
