# Subroutine of pkg-source-build-init-routine
# Purpose is to install proper package dependencies regardless of operating system.
---
- name: Ensure required packages are installed with apt-get
  ansible.builtin.apt:
    name: "{{ item if not item.endswith('.deb') else omit }}"
    deb: "{{ item if item.endswith('.deb') else omit }}"
    state: "{{ pkg_manager_state }}"
    update_cache: "{{ pkg_manager_update_cache }}"
  loop: "{{ pkg_manager_pkgs if pkg_manager_pkgs is list else [pkg_manager_pkgs] }}"
