# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later

# Subroutine of pkg-source-build-init-routine
# Purpose is to install proper package dependencies regardless of operating system.
---
- name: Package Manager Switch
  block:
    - name: Print Packages to Install with apt-get
      ansible.builtin.debug:
        msg: "{{ pkg_manager_pkgs.apt }}"
      when: ansible_facts['os_family']|lower == 'debian' and pkgs.apt is defined

    - name: Ensure required packages are installed with apt-get
      ansible.builtin.apt:
        pkg: "{{ pkg_manager_pkgs.apt }}"
        state: present
        update_cache: true
      when: ansible_facts['os_family']|lower == 'debian' and pkgs.apt is defined

    - name: Ensure required packages are installed with dnf
      ansible.builtin.dnf:
        name: "{{ pkg_manager_pkgs.dnf }}"
        state: present
      when: ansible_facts['os_family']|lower == 'redhat' and pkgs.def is defined

    - name: Ensure required packages are installed with pacman
      community.general.pacman:
        name: "{{ pkg_manager_pkgs.pacman }}"
        state: present
        update_cache: true
      when: ansible_facts['os_family']|lower == 'archlinux' and pkgs.pacman is defined
